format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$docker_context\
$package\
$buf\
$nix_shell\
$conda\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character"""

## Prompt

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vicmd_symbol = "[â®](green)"

## Before Programming Languages

[directory]
read_only = " ï ½"
style = "bold blue"
truncation_symbol = "â€¦/"

[git_branch]
format = "[ï‘„](bright-black) [$symbol]($style)[$branch](bright-black)"
style = "purple"
symbol = "ï˜ "

[git_status]
# format = "([$all_status$ahead_behind]($style) )"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](purple) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "â€‹" # "="
untracked = "â€‹" # "ï™"
modified = "â€‹" # "*"
stashed = "â‰¡"
staged = "â€‹" # "+"
renamed = "â€‹" # "Â»"
deleted = "â€‹" # "âœ˜"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"


## After Programming Languages

[docker_context]
format = "[ï‘„](bright-black) [$symbol]($style)[$context](bright-black) "
style = "cyan"
symbol = "ïŒˆ "

[package]
format = "[ï‘„](bright-black) [$symbol]($style)[$version](bright-black) "
style = "dark-white"
symbol = "ï£– "

[memory_usage]
symbol = "ï¡š "

[cmd_duration]
format = "[ï‘„](bright-black) [î…]($style) [$duration](bright-black) "
style = "yellow"
show_notifications = true
min_time_to_notify = 30000

[[battery.display]]
threshold = 15


## Languages

[aws]
symbol = "îŒ½  "

[bun]
format = "[ï‘„](bright-black) [$symbol]($style)"

[buf]
format = "[ï‘„](bright-black) [$symbol]($style)"
symbol = "ï’ "

[c]
format = "[ï‘„](bright-black) [$symbol]($style)"
symbol = "î˜ "

[cmake]
format = "[ï‘„](bright-black) [$symbol]($style)"

[cobol]
format = "[ï‘„](bright-black) [$symbol]($style)"

[conda]
format = "[ï‘„](bright-black) [$symbol]($style)"
symbol = "ï„Œ "

[crystal]
format = "[ï‘„](bright-black) [$symbol]($style)"

[daml]
format = "[ï‘„](bright-black) [$symbol]($style)"

[dart]
format = "[ï‘„](bright-black) [$symbol]($style)"
symbol = "î˜ "

[deno]
format = "[ï‘„](bright-black) [$symbol]($style)"

[dotnet]
format = "[ï‘„](bright-black) [$symbol]($style)"
symbol = "î¿ "

[elixir]
format = "[ï‘„](bright-black) [$symbol]($style)"
symbol = "î‰µ "

[elm]
format = "[ï‘„](bright-black) [$symbol]($style)"
symbol = "î˜¬ "

[erlang]
format = '[ï‘„](bright-black) [$symbol]($style)'

[golang]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "î˜§ "

[haskell]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "î· "

[helm]
format = '[ï‘„](bright-black) [$symbol]($style)'

[hg_branch]
format = "[ï‘„](bright-black) [$symbol$branch]($style) "
symbol = "ï˜ "

[java]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "î‰– "

[julia]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "î˜¤ "

[kotlin]
format = '[ï‘„](bright-black) [$symbol]($style)'

[lua]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "î˜  "

[nim]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "ïš¤ "

[nix_shell]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "ïŒ“ "

[nodejs]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "îœ˜ "

[ocaml]
format = '[ï‘„](bright-black) [$symbol(\($switch_indicator$switch_name\) )]($style)'

[perl]
format = '[ï‘„](bright-black) [$symbol]($style)'

[php]
format = '[ï‘„](bright-black) [$symbol]($style)'

[pulumi]
format = '[ï‘„](bright-black) [$symbol$stack]($style)'

[purescript]
format = '[ï‘„](bright-black) [$symbol]($style)'

[python]
format = '[ï‘„](bright-black) [$symbol]($style)[( $virtualenv)](bright-black)'
symbol = "îˆµ "

[raku]
format = '[ï‘„](bright-black) [$symbol]($style)'

[red]
format = '[ï‘„](bright-black) [$symbol]($style)'

[rlang]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "ï³’ "

[ruby]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "î‘ "

[rust]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "î¨ "

[swift]
format = '[ï‘„](bright-black) [$symbol]($style)'

[spack]
format = '[ï‘„](bright-black) [$symbol]($style)'
symbol = "ğŸ…¢ "

[vagrant]
format = '[ï‘„](bright-black) [$symbol]($style)'

[vlang]
format = '[ï‘„](bright-black) [$symbol]($style)'

[zig]
format = '[ï‘„](bright-black) [$symbol]($style)'
